//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPTStudio.TelegramProvider.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPTStudio.TelegramProvider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #version: 0.2
        ///Ġ t
        ///Ġ a
        ///h e
        ///i n
        ///r e
        ///o n
        ///Ġt he
        ///e r
        ///Ġ s
        ///a t
        ///Ġ w
        ///Ġ o
        ///e n
        ///Ġ c
        ///i t
        ///i s
        ///a n
        ///o r
        ///e s
        ///Ġ b
        ///e d
        ///Ġ f
        ///in g
        ///Ġ p
        ///o u
        ///Ġa n
        ///a l
        ///a r
        ///Ġt o
        ///Ġ m
        ///Ġo f
        ///Ġ in
        ///Ġ d
        ///Ġ h
        ///Ġan d
        ///i c
        ///a s
        ///l e
        ///Ġt h
        ///i on
        ///o m
        ///l l
        ///en t
        ///Ġ n
        ///Ġ l
        ///s t
        ///Ġ re
        ///v e
        ///Ġ e
        ///r o
        ///l y
        ///Ġb e
        ///Ġ g
        ///Ġ T
        ///c t
        ///Ġ S
        ///i d
        ///o t
        ///Ġ I
        ///u t
        ///e t
        ///Ġ A
        ///Ġ is
        ///Ġ on
        ///i m
        ///a m
        ///o w
        ///a y
        ///a d
        ///s e
        ///Ġth at
        ///Ġ C
        ///i g
        ///Ġf or
        ///a c
        ///Ġ y
        ///v er
        ///u r
        ///Ġ u
        ///l d
        ///Ġs t
        ///Ġ M
        ///&apos; s
        ///Ġ he
        ///Ġ it
        ///at ion
        ///it h
        ///i r
        ///c e
        ///Ġy ou
        ///i l
        ///Ġ B
        ///Ġw h
        ///o l
        ///Ġ P
        ///Ġw ith
        ///Ġ 1
        ///t er
        ///c h
        ///Ġa s
        ///Ġw e
        ///Ġ (
        ///n d
        ///i ll
        ///Ġ D
        ///i f
        ///Ġ 2
        ///a g
        ///er s
        ///k e
        ///Ġ &quot;
        ///Ġ H
        ///e m
        ///Ġc on
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TokenizerMerges {
            get {
                return ResourceManager.GetString("TokenizerMerges", resourceCulture);
            }
        }
    }
}
